name: mayajaal
description: Mayajaal video streaming app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.3.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.4
  webview_flutter_android: ^3.16.0
  cupertino_icons: ^1.0.8

flutter:
  uses-material-design: true
